REGION_TO_CITIES = {
    "Domestic US": [
        "New York, USA", "Los Angeles, USA", "Chicago, USA", "San Francisco, USA",
        "Miami, USA", "Dallas, USA", "Houston, USA", "Seattle, USA", "Atlanta, USA",
        "Boston, USA", "Denver, USA", "Las Vegas, USA", "Philadelphia, USA"
    ],
    "Europe": [
        "Paris, France", "Berlin, Germany", "Madrid, Spain", "Rome, Italy", "London, UK",
        "Amsterdam, Netherlands", "Vienna, Austria", "Stockholm, Sweden", "Dublin, Ireland",
        "Zurich, Switzerland", "Brussels, Belgium", "Lisbon, Portugal", "Warsaw, Poland",
        "Athens, Greece", "Prague, Czech Republic", "Oslo, Norway"
    ],
    "East Asia": [
        "Shanghai, China", "Beijing, China", "Tokyo, Japan", "Osaka, Japan",
        "Seoul, South Korea", "Hong Kong, China", "Taipei, Taiwan",
        "Shenzhen, China", "Guangzhou, China", "Chengdu, China"
    ],
    "South Asia": [
        "Mumbai, India", "New Delhi, India", "Bangalore, India", "Chennai, India",
        "Hyderabad, India", "Kolkata, India", "Dhaka, Bangladesh", "Karachi, Pakistan"
    ],
    "Southeast Asia": [
        "Singapore, Singapore", "Jakarta, Indonesia", "Bangkok, Thailand",
        "Kuala Lumpur, Malaysia", "Ho Chi Minh City, Vietnam", "Hanoi, Vietnam",
        "Manila, Philippines", "Phnom Penh, Cambodia"
    ],
    "South America": [
        "São Paulo, Brazil", "Rio de Janeiro, Brazil", "Buenos Aires, Argentina",
        "Santiago, Chile", "Bogotá, Colombia", "Lima, Peru", "Quito, Ecuador",
        "Montevideo, Uruguay", "Caracas, Venezuela"
    ],
    "Middle East": [
        "Dubai, UAE", "Abu Dhabi, UAE", "Riyadh, Saudi Arabia", "Jeddah, Saudi Arabia",
        "Doha, Qatar", "Kuwait City, Kuwait", "Manama, Bahrain", "Muscat, Oman",
        "Istanbul, Turkey", "Tehran, Iran"
    ],
    "Africa": [
        "Johannesburg, South Africa", "Cape Town, South Africa", "Lagos, Nigeria",
        "Nairobi, Kenya", "Cairo, Egypt", "Casablanca, Morocco", "Accra, Ghana",
        "Addis Ababa, Ethiopia", "Dar es Salaam, Tanzania", "Algiers, Algeria"
    ],
    "Oceania": [
        "Sydney, Australia", "Melbourne, Australia", "Brisbane, Australia",
        "Auckland, New Zealand", "Wellington, New Zealand", "Perth, Australia"
    ],
    "Russia & Central Asia": [
        "Moscow, Russia", "Saint Petersburg, Russia", "Almaty, Kazakhstan",
        "Tashkent, Uzbekistan", "Baku, Azerbaijan", "Bishkek, Kyrgyzstan",
        "Yerevan, Armenia"
    ],
    "Offshore Banking": [
        "Cayman Islands", "British Virgin Islands", "Bahamas", "Panama",
        "Switzerland", "Luxembourg", "Liechtenstein", "Hong Kong", "Singapore",
        "Dubai, UAE", "Seychelles", "Mauritius", "Isle of Man", "Monaco",
        "Andorra", "Vanuatu", "Bermuda", "Cook Islands", "Labuan, Malaysia"
    ]
}

LOCATION_TO_IP_RANGES = {
    # Domestic US
    "New York, USA": "73.56",
    "Los Angeles, USA": "172.58",
    "Chicago, USA": "98.23",
    "San Francisco, USA": "66.50",
    "Miami, USA": "79.45",
    "Dallas, USA": "104.12",
    "Houston, USA": "107.89",
    "Seattle, USA": "23.76",
    "Atlanta, USA": "68.90",
    "Boston, USA": "12.34",
    "Denver, USA": "45.67",
    "Las Vegas, USA": "128.90",
    "Philadelphia, USA": "150.12",
    # Europe
    "Paris, France": "51.75",
    "Berlin, Germany": "88.99",
    "Madrid, Spain": "213.97",
    "Rome, Italy": "151.13",
    "London, UK": "81.22",
    "Amsterdam, Netherlands": "83.45",
    "Vienna, Austria": "84.56",
    "Stockholm, Sweden": "85.67",
    "Dublin, Ireland": "86.78",
    "Zurich, Switzerland": "87.89",
    "Brussels, Belgium": "88.90",
    "Lisbon, Portugal": "89.01",
    "Warsaw, Poland": "90.12",
    "Athens, Greece": "91.23",
    "Prague, Czech Republic": "92.34",
    "Oslo, Norway": "93.45",
    # East Asia
    "Shanghai, China": "203.195",
    "Beijing, China": "203.196",
    "Tokyo, Japan": "210.153",
    "Osaka, Japan": "210.154",
    "Seoul, South Korea": "121.254",
    "Hong Kong, China": "211.165",
    "Taipei, Taiwan": "212.176",
    "Shenzhen, China": "203.197",
    "Guangzhou, China": "203.198",
    "Chengdu, China": "203.199",
    # South Asia
    "Mumbai, India": "102.34",
    "New Delhi, India": "102.35",
    "Bangalore, India": "102.36",
    "Chennai, India": "102.37",
    "Hyderabad, India": "102.38",
    "Kolkata, India": "102.39",
    "Dhaka, Bangladesh": "103.40",
    "Karachi, Pakistan": "104.41",
    # Southeast Asia
    "Singapore, Singapore": "115.56",
    "Jakarta, Indonesia": "116.67",
    "Bangkok, Thailand": "117.78",
    "Kuala Lumpur, Malaysia": "118.89",
    "Ho Chi Minh City, Vietnam": "119.90",
    "Hanoi, Vietnam": "120.01",
    "Manila, Philippines": "121.12",
    "Phnom Penh, Cambodia": "122.23",
    # South America
    "São Paulo, Brazil": "200.98",
    "Rio de Janeiro, Brazil": "201.99",
    "Buenos Aires, Argentina": "190.3",
    "Santiago, Chile": "202.88",
    "Bogotá, Colombia": "203.77",
    "Lima, Peru": "204.66",
    "Quito, Ecuador": "205.55",
    "Montevideo, Uruguay": "206.44",
    "Caracas, Venezuela": "207.33",
    # Middle East
    "Dubai, UAE": "94.200",
    "Abu Dhabi, UAE": "95.201",
    "Riyadh, Saudi Arabia": "188.48",
    "Jeddah, Saudi Arabia": "189.49",
    "Doha, Qatar": "190.60",
    "Kuwait City, Kuwait": "191.71",
    "Manama, Bahrain": "192.82",
    "Muscat, Oman": "193.93",
    "Istanbul, Turkey": "194.04",
    "Tehran, Iran": "195.15",
    # Africa
    "Johannesburg, South Africa": "210.16",
    "Cape Town, South Africa": "210.17",
    "Lagos, Nigeria": "210.18",
    "Nairobi, Kenya": "210.19",
    "Cairo, Egypt": "210.20",
    "Casablanca, Morocco": "210.21",
    "Accra, Ghana": "210.22",
    "Addis Ababa, Ethiopia": "210.23",
    "Dar es Salaam, Tanzania": "210.24",
    "Algiers, Algeria": "210.25",
    # Oceania
    "Sydney, Australia": "220.26",
    "Melbourne, Australia": "220.27",
    "Brisbane, Australia": "220.28",
    "Auckland, New Zealand": "220.29",
    "Wellington, New Zealand": "220.30",
    "Perth, Australia": "220.31",
    # Russia & Central Asia
    "Moscow, Russia": "230.32",
    "Saint Petersburg, Russia": "230.33",
    "Almaty, Kazakhstan": "230.34",
    "Tashkent, Uzbekistan": "230.35",
    "Baku, Azerbaijan": "230.36",
    "Bishkek, Kyrgyzstan": "230.37",
    "Yerevan, Armenia": "230.38",
    # Offshore Banking
    "Cayman Islands": "240.39",
    "British Virgin Islands": "240.40",
    "Bahamas": "240.41",
    "Panama": "240.42",
    "Switzerland": "240.43",
    "Luxembourg": "240.44",
    "Liechtenstein": "240.45",
    "Hong Kong": "240.46",
    "Singapore": "240.47",
    "Seychelles": "240.48",
    "Mauritius": "240.49",
    "Isle of Man": "240.50",
    "Monaco": "240.51",
    "Andorra": "240.52",
    "Vanuatu": "240.53",
    "Bermuda": "240.54",
    "Cook Islands": "240.55",
    "Labuan, Malaysia": "240.56"
}

TIMEZONE_MAPPING = {
    # Domestic US
    "New York, USA": "America/New_York",
    "Los Angeles, USA": "America/Los_Angeles",
    "Chicago, USA": "America/Chicago",
    "San Francisco, USA": "America/Los_Angeles",
    "Miami, USA": "America/New_York",
    "Dallas, USA": "America/Chicago",
    "Houston, USA": "America/Chicago",
    "Seattle, USA": "America/Los_Angeles",
    "Atlanta, USA": "America/New_York",
    "Boston, USA": "America/New_York",
    "Denver, USA": "America/Denver",
    "Las Vegas, USA": "America/Los_Angeles",
    "Philadelphia, USA": "America/New_York",
    # Europe
    "Paris, France": "Europe/Paris",
    "Berlin, Germany": "Europe/Berlin",
    "Madrid, Spain": "Europe/Madrid",
    "Rome, Italy": "Europe/Rome",
    "London, UK": "Europe/London",
    "Amsterdam, Netherlands": "Europe/Amsterdam",
    "Vienna, Austria": "Europe/Vienna",
    "Stockholm, Sweden": "Europe/Stockholm",
    "Dublin, Ireland": "Europe/Dublin",
    "Zurich, Switzerland": "Europe/Zurich",
    "Brussels, Belgium": "Europe/Brussels",
    "Lisbon, Portugal": "Europe/Lisbon",
    "Warsaw, Poland": "Europe/Warsaw",
    "Athens, Greece": "Europe/Athens",
    "Prague, Czech Republic": "Europe/Prague",
    "Oslo, Norway": "Europe/Oslo",
    # East Asia
    "Shanghai, China": "Asia/Shanghai",
    "Beijing, China": "Asia/Shanghai",
    "Tokyo, Japan": "Asia/Tokyo",
    "Osaka, Japan": "Asia/Tokyo",
    "Seoul, South Korea": "Asia/Seoul",
    "Hong Kong, China": "Asia/Hong_Kong",
    "Taipei, Taiwan": "Asia/Taipei",
    "Shenzhen, China": "Asia/Shanghai",
    "Guangzhou, China": "Asia/Shanghai",
    "Chengdu, China": "Asia/Shanghai",
    # South Asia
    "Mumbai, India": "Asia/Kolkata",
    "New Delhi, India": "Asia/Kolkata",
    "Bangalore, India": "Asia/Kolkata",
    "Chennai, India": "Asia/Kolkata",
    "Hyderabad, India": "Asia/Kolkata",
    "Kolkata, India": "Asia/Kolkata",
    "Dhaka, Bangladesh": "Asia/Dhaka",
    "Karachi, Pakistan": "Asia/Karachi",
    # Southeast Asia
    "Singapore, Singapore": "Asia/Singapore",
    "Jakarta, Indonesia": "Asia/Jakarta",
    "Bangkok, Thailand": "Asia/Bangkok",
    "Kuala Lumpur, Malaysia": "Asia/Kuala_Lumpur",
    "Ho Chi Minh City, Vietnam": "Asia/Ho_Chi_Minh",
    "Hanoi, Vietnam": "Asia/Ho_Chi_Minh",
    "Manila, Philippines": "Asia/Manila",
    "Phnom Penh, Cambodia": "Asia/Phnom_Penh",
    # South America
    "São Paulo, Brazil": "America/Sao_Paulo",
    "Rio de Janeiro, Brazil": "America/Sao_Paulo",
    "Buenos Aires, Argentina": "America/Argentina/Buenos_Aires",
    "Santiago, Chile": "America/Santiago",
    "Bogotá, Colombia": "America/Bogota",
    "Lima, Peru": "America/Lima",
    "Quito, Ecuador": "America/Guayaquil",
    "Montevideo, Uruguay": "America/Montevideo",
    "Caracas, Venezuela": "America/Caracas",
    # Middle East
    "Dubai, UAE": "Asia/Dubai",
    "Abu Dhabi, UAE": "Asia/Dubai",
    "Riyadh, Saudi Arabia": "Asia/Riyadh",
    "Jeddah, Saudi Arabia": "Asia/Riyadh",
    "Doha, Qatar": "Asia/Qatar",
    "Kuwait City, Kuwait": "Asia/Kuwait",
    "Manama, Bahrain": "Asia/Bahrain",
    "Muscat, Oman": "Asia/Muscat",
    "Istanbul, Turkey": "Europe/Istanbul",
    "Tehran, Iran": "Asia/Tehran",
    # Africa
    "Johannesburg, South Africa": "Africa/Johannesburg",
    "Cape Town, South Africa": "Africa/Johannesburg",
    "Lagos, Nigeria": "Africa/Lagos",
    "Nairobi, Kenya": "Africa/Nairobi",
    "Cairo, Egypt": "Africa/Cairo",
    "Casablanca, Morocco": "Africa/Casablanca",
    "Accra, Ghana": "Africa/Accra",
    "Addis Ababa, Ethiopia": "Africa/Addis_Ababa",
    "Dar es Salaam, Tanzania": "Africa/Dar_es_Salaam",
    "Algiers, Algeria": "Africa/Algiers",
    # Oceania
    "Sydney, Australia": "Australia/Sydney",
    "Melbourne, Australia": "Australia/Melbourne",
    "Brisbane, Australia": "Australia/Brisbane",
    "Auckland, New Zealand": "Pacific/Auckland",
    "Wellington, New Zealand": "Pacific/Auckland",
    "Perth, Australia": "Australia/Perth",
    # Russia & Central Asia
    "Moscow, Russia": "Europe/Moscow",
    "Saint Petersburg, Russia": "Europe/Moscow",
    "Almaty, Kazakhstan": "Asia/Almaty",
    "Tashkent, Uzbekistan": "Asia/Tashkent",
    "Baku, Azerbaijan": "Asia/Baku",
    "Bishkek, Kyrgyzstan": "Asia/Bishkek",
    "Yerevan, Armenia": "Asia/Yerevan",
    # Offshore Banking
    "Cayman Islands": "America/Cayman",
    "British Virgin Islands": "America/Tortola",
    "Bahamas": "America/Nassau",
    "Panama": "America/Panama",
    "Switzerland": "Europe/Zurich",
    "Luxembourg": "Europe/Luxembourg",
    "Liechtenstein": "Europe/Vaduz",
    "Hong Kong": "Asia/Hong_Kong",
    "Singapore": "Asia/Singapore",
    "Seychelles": "Indian/Mahe",
    "Mauritius": "Indian/Mauritius",
    "Isle of Man": "Europe/London",
    "Monaco": "Europe/Monaco",
    "Andorra": "Europe/Andorra",
    "Vanuatu": "Pacific/Efate",
    "Bermuda": "Atlantic/Bermuda",
    "Cook Islands": "Pacific/Rarotonga",
    "Labuan, Malaysia": "Asia/Kuala_Lumpur"
}
